#!/usr/bin/env node
/*
 * weekly-report.mjs — the Monday board pack.
 *
 * Pulls live analytics (analytics-self), CRM pipeline counts (get-clients),
 * and outreach stats (get-outreach-status) when ADMIN_PASSWORD is set, and
 * writes docs/reports/YYYY-WW.md: headline numbers, what moved, the CEO's
 * call for next week, one experiment. Each exec contributes a section. Kept
 * under one page. No em dashes.
 *
 * Run: ADMIN_PASSWORD=... node scripts/weekly-report.mjs
 * Offline (no creds) it still writes the skeleton with 'no data' markers so
 * the ritual never silently skips.
 */
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const SITE = process.env.URL || 'https://staticswift.co.uk';
const PW = process.env.ADMIN_PASSWORD;

function isoWeek(d) {
  const date = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
  const day = date.getUTCDay() || 7;
  date.setUTCDate(date.getUTCDate() + 4 - day);
  const yearStart = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
  const week = Math.ceil((((date - yearStart) / 86400000) + 1) / 7);
  return { year: date.getUTCFullYear(), week };
}

async function get(fn, opts = {}) {
  if (!PW) return null;
  try {
    const r = await fetch(SITE + '/.netlify/functions/' + fn, {
      headers: { 'x-admin-password': PW, ...(opts.headers || {}) },
      ...(opts.method ? { method: opts.method } : {}),
    });
    return r.ok ? await r.json() : null;
  } catch { return null; }
}

const n = (v, d = 'no data') => (v === 0 || v ? String(v) : d);

async function main() {
  const now = new Date();
  const { year, week } = isoWeek(now);
  const ww = String(week).padStart(2, '0');

  const analytics = await get('analytics-self?days=7');
  const clientsRes = await get('get-clients');
  const outreach = await get('get-outreach-status');

  const clients = Array.isArray(clientsRes?.clients) ? clientsRes.clients : (Array.isArray(clientsRes) ? clientsRes : []);
  const stageCount = {};
  for (const c of clients) { const s = (c.stage || 'unknown'); stageCount[s] = (stageCount[s] || 0) + 1; }
  const newThisWeek = clients.filter(c => {
    const t = Date.parse(c.createdAt || c.addedAt || 0);
    return t && (now - t) < 7 * 86400000;
  }).length;

  const ov = analytics?.overview || {};
  const funnel = analytics?.funnel || [];
  const geo = analytics?.geoSplit || {};
  const topPages = (analytics?.topPages || []).slice(0, 5);

  const md = `# StaticSwift Board Pack · ${year}-W${ww}

Generated ${now.toISOString().slice(0, 16).replace('T', ' ')} UTC. One page. Numbers are live where available.

## Headline

- Sessions (7d): **${n(ov.sessions)}** · visitors ${n(ov.visitors)} · pageviews ${n(ov.pageviews)}
- Avg time on page: ${n(ov.avgDuration, "no data")} (sec) · bounce ${n(ov.bounceRate)}%
- Form submits (7d): **${n(ov.formSubmits)}** · WhatsApp/tel CTA clicks ${n(ov.ctaClicks)}
- New CRM leads this week: **${newThisWeek}** · total in pipeline ${clients.length}
- Geo split: UK ${n(geo.uk)} / non-UK ${n(geo.nonUk)} / unknown ${n(geo.unknown)}

## Funnel (per session, 7d)

${funnel.length ? funnel.map(f => `- ${f.label}: ${f.count}`).join('\n') : '- no data (analytics endpoint unreachable)'}

## CRM pipeline

${Object.keys(stageCount).length ? Object.entries(stageCount).sort((a, b) => b[1] - a[1]).map(([s, c]) => `- ${s}: ${c}`).join('\n') : '- no data'}

## Outreach (Head of Outreach)

- Prospects in pipeline: ${n(outreach?.total ?? (Array.isArray(outreach?.prospects) ? outreach.prospects.length : null))}
- Approval queue: see admin · sends are gated until 50 clean approvals per category
- Reminder: 30 sends/day cap until DKIM/DMARC re-checked (deliverability.js)

## Top pages (SEO Director)

${topPages.length ? topPages.map(p => `- ${p.path} · ${p.views} views`).join('\n') : '- no data'}

## What moved this week

- _CEO to fill: the one number that changed and why._

## CEO's call for next week

- _The single change to make. Revenue this month beats elegance, never at the cost of de-indexing or brand credibility._

## One experiment

- _One testable bet, with the metric that decides it._

---
Sections: CRO (funnel), SEO Director (top pages), Head of Outreach (outreach),
Head of Analytics (headline), CEO (call + experiment). CFO: no invoices to
reconcile yet. Generated by scripts/weekly-report.mjs.
`;

  mkdirSync(join(ROOT, 'docs/reports'), { recursive: true });
  const path = join(ROOT, 'docs/reports', `${year}-W${ww}.md`);
  writeFileSync(path, md);
  console.log('wrote docs/reports/' + year + '-W' + ww + '.md' + (PW ? '' : ' (skeleton; set ADMIN_PASSWORD for live numbers)'));
}
main();
